### ISSUE TITLE
Date not visible on top of post

### ISSUE THREAD

**Issue by rahulpathakgit** [bijumon/oct2#12]
![screenshot from 2017-07-27 01-31-11](https://user-images.githubusercontent.com/10892516/28641058-72c16be4-726b-11e7-81ea-765c09f9b213.png)

I am trying your theme for my first octopress blog but I am not able to get the date on the top of post. Am I missing something?

**Comment by bijumon** [comment]
haven't used octopress in ages, sorry. no idea whats going on here
